server {
    listen 80;
    server_name localhost;

    # Frontend de Vite (Static Files servidos por el contenedor de Frontend)
    location / {
        proxy_pass http://frontend:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Proxy para la API de PocketBase (Previene errores de CORS en peticiones complejas)
    location /api/ {
        proxy_pass http://pocketbase:8090/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Proxy para el Panel de Administración de PocketBase
    location /_/ {
        proxy_pass http://pocketbase:8090/_/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
