worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    
    sendfile        on;
    keepalive_timeout  65;

    # Axis 5: Asegura que Nginx acepte 100M para permitir fotos de alta gama
    client_max_body_size 100M;

    server {
        listen       80;
        server_name  localhost capimercado.com www.capimercado.com;
        root   /usr/share/nginx/html;
        index  index.html index.htm;

        location / {
            try_files $uri $uri/ /index.html;
        }

        # Proxy al PocketBase
        location /api/ {
            proxy_pass http://pocketbase:8090/api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        
        location /_/ {
            proxy_pass http://pocketbase:8090/_/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        
        location /pocketbase-files/ {
            proxy_pass http://pocketbase:8090/;
        }
    }
}
